[platformio]
default_envs = lab4_3

[env]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4

[env:lab4_3]
build_src_filter = +<lab4_3/>

[env:lab4_4]
build_src_filter = +<lab4_4/>

[env:lab4_6]
build_src_filter = +<lab4_6/>
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit SHTC3 Library@^1.0.1